apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: acm
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/kahowell/ai-grid-tenant.git
    targetRevision: HEAD
    path: apps/acm/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: open-cluster-management
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 10m
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
