apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: acm-observability-thanos
  namespace: open-cluster-management-observability
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  generateBucketName: acm-observability-thanos
