apiVersion: monitoring.rhobs/v1alpha1
kind: ScrapeConfig
metadata:
  name: rhai-metrics
  namespace: open-cluster-management-observability
  labels:
    app.kubernetes.io/component: user-workload-metrics-collector
spec:
  jobName: rhai-metrics
  metricsPath: /metrics
  params:
    match[]:
      - '{__name__=~".*"}' # PromQL matchers
  scheme: HTTP
  staticConfigs:
    - targets:
        - data-science-collector-collector.redhat-ods-monitoring.svc:8890
