skipCrdCheck: true
profile: maas
operator:
  type: rhoai
  # values.yaml
components:
  dashboard:
    dsc:
      managementState: Managed
  kserve:
    gateway:
      spec:
        listeners:
          - name: https
            port: 443
            # hostname: <HOSTNAME> # Uncomment this line to use a specific hostname.
            protocol: HTTPS
            allowedRoutes:
              namespaces:
                # The following is an example of how to restrict the namespaces to the interested ones.
                from: Selector
                selector:
                  matchExpressions:
                  - key: kubernetes.io/metadata.name
                    operator: In
                    values:
                    - openshift-ingress
                    # TODO - <LLM_INFERENCE_SERVICE_NAMESPACE>
  aigateway:
    modelsAsAService:
      gateway:
        spec:
          listeners:
            - name: https
              port: 443
              # hostname: <HOSTNAME> # Uncomment this line to use a specific hostname.
              protocol: HTTPS
              allowedRoutes:
                namespaces:
                  # The following is an example of how to restrict the namespaces to the interested ones.
                  from: Selector
                  selector:
                    matchExpressions:
                    - key: kubernetes.io/metadata.name
                      operator: In
                      values:
                      - openshift-ingress
                      # TODO - <LLM_INFERENCE_SERVICE_NAMESPACE>
